apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
  labels:
    app: account-service
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
      - name: account-service
        image: navuitag/account-service:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 9080
---
apiVersion: v1
kind: Service
metadata:
  name: account-service
  labels:
    app: account-service
    tier: backend
spec:
  selector:
    app: account-service
  type: NodePort
  ports:
  - port: 9080
    targetPort: 9080
    nodePort: 30001
